services:
  nextjs:
    build:
      dockerfile: "./Dockerfile.nextjs"
    container_name: nextjs-tree-table-demo-nextjs
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.4
    container_name: nextjs-tree-table-demo-database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword-nextjs
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysql", "-u", "user", "-ppassword", "database", "-e", "select 1;"]
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s
  
networks:
  default:
    name: nextjs-tree-table-demo-network
